from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from . import db

"""Model for storing the images
  Three Models 
  1. Image
  2. Child
  3. Match

"""
class Image(db.Model):
    """
    id contains the unique id generated by the server for storing images for the furthur use
    im_land_centrod is one of the features we have calculated using the landmarks of the face whihc is used to find the images quickly
    gender is also used to find the relative images quickly
    age is also used to find the images quickly
    """
    id = db.Column(db.String,primary_key=True)
    im_land_centroid = db.Column(db.Integer)
    gender = db.Column(db.Integer)
    age = db.Column(db.Integer)
    child = db.relationship('Child',backref='child_identity',uselist=False)
    matches = db.relationship('Match',backref='match_image')

class Child(db.Model):
    """
    we have the attributes id,name,age,image_url,face_id
    """
    id = db.Colum(db.Integer,primary_key=True)
    name = db.Column(db.String)
    age = db.Column(db.Integer)
    image_url = db.Column(db.String)
    face_id = db.Column(db.String,db.ForeignKey('image.id'))

class Match(db.Model):
    """
    we have attributes such as id,match_id both are uique which are generated by the server
    """
    id = db.Column(db.String,primary_key=True)
    match_id = db.Column(db.String,db.ForeignKey('image.id'))


