from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from . import db

"""Model for storing the images
  Three Models 
  1. Child
  2. Match
"""


class Child(db.Model):
    """
    we have the attributes id,name,age,image_url,face_id
    id contains the unique id generated by the server for storing images for the furthur use
    im_land_centrod is one of the features we have calculated using the landmarks of the face whihc is used to find the images quickly
    gender is also used to find the relative images quickly
    age is also used to find the images quickly
    """
    c_fid = db.Colum(db.String,primary_key=True)
    im_land_centroid = db.Column(db.Integer)
    name = db.Column(db.String)
    age = db.Column(db.Integer)
    image_url = db.Column(db.String)
    gender = db.Column(db.String)
    matches = db.relationship('Match',backref='match_images')

class Match(db.Model):
    """
    we have attributes such as fid,match_id both are uique which are generated by the server
    """
    m_fid = db.Column(db.String,primary_key=True)
    im_land_centroid = db.Column(db.Integer)
    age = db.Column(db.Integer)
    image_url = db.Column(db.String)
    gender = db.Column(db.String)
    c_m_fid = db.Column(db.String,db.ForeignKey('Child.c_fid'),nullable = False)

"""
many to many relationship between the match and the child table
creating a association table for the matches and the images
"""
# image_matches = db.Table('image_matches',
# db.Column('c_fid',db.String,db.ForeignKey('child.c_fid'),primary_key=True),
# db.Column('m_fid',db.String,db.ForeignKey('match.m_fid'),primary_key=True)
# )


